version: "2"
run:
  tests: true
linters:
  enable:
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 35
    revive:
      rules:
        - name: var-naming
        - name: blank-imports
        - name: empty-lines
        - name: increment-decrement
        - name: indent-error-flow
        - name: early-return
        - name: range
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
